branch: true
excl-start: "#\\[cfg\\(test\\)\\]"
excl-end: "end tests"
filter: covered
ignore:
  - "**/.cargo/registry/**/*"
  - "/rustc/**/*"
ignore-not-existing: true
llvm: true
output-type: lcov
output-path: ./lcov.info
