name: Rust

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
env:
  CARGO_INCREMENTAL: '0'
  RUSTFLAGS: '-Ccodegen-units=1 -Cinstrument-coverage -Clink-dead-code -Copt-level=0 -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests -Zprofile'
  RUSTDOCFLAGS: '-Ccodegen-units=1 -Cinstrument-coverage -Clink-dead-code -Copt-level=0 -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests -Zprofile'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        profile: default
    - name: Test and generate coverage report
      run: ./coverage-run.sh
    - name: Build documentation
      run: cargo doc --verbose
    - name: Upload coverage report to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: lcov.info
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features
