name: Rust

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
env:
  CARGO_INCREMENTAL: '0'
  RUSTFLAGS: '-Ccodegen-units=1 -Cinstrument-coverage -Copt-level=0'
  RUSTDOCFLAGS: '-Ccodegen-units=1 -Cinstrument-coverage -Copt-level=0'

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust nightly
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
        components: "clippy,rustfmt"
    - name: Install LLVM 18
      run: |
        echo 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main' | sudo tee -a /etc/apt/sources.list
        echo 'deb-src http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main' | sudo tee -a /etc/apt/sources.list
        sudo apt-get install -y gnupg2
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo apt-get update -y
        sudo apt-get install -y llvm-18
        sudo ln -s /usr/lib/llvm-18/bin/* /usr/bin
    - name: Install coverage-run dependencies
      run: |
        python3 -m venv venv
        VIRTUAL_ENV="$PWD/venv" PATH="$PWD/venv/bin:$PATH" $PWD/venv/bin/pip3 install toml
        cargo install rustfilt
    - name: Run Clippy check.
      run: |
        cargo clippy -- -Dwarnings
    - name: Run formatting check.
      run: cargo fmt --check
    - name: Build and test with coverage data
      run: VIRTUAL_ENV="$PWD/venv" PATH="$PWD/venv/bin:$PATH" $PWD/venv/bin/python3 ./coverage-run.py --no-open --no-html
    - name: Combine coverage reports
      run: cat scratchstack-arn.lcov scratchstack-aws-principal.lcov > scratchstack-core.lcov
    - name: Upload coverage report to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: scratchstack-core.lcov
